config/routes.rb
Dsg::Application.routes.draw do
  resources :mtb_among_card_types

  resources :mtb_among_card_expantions

  resources :mtb_cards

  resources :mtb_expantions

  resources :mtb_publishers

  resources :mtb_card_types

  match ':controller(/:action(/:id))(.:format)'
end

app/models/mtb_expantion.rb
class MtbExpantion < ActiveRecord::Base
  attr_accessible :mtb_publisher_id, :name, :released_at
end

app/controllers/mtb_expantions_controller.rb
class MtbExpantionsController < ApplicationController
  # GET /mtb_expantions
  # GET /mtb_expantions.json
  def index
    @mtb_expantions = MtbExpantion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mtb_expantions }
    end
  end

  # GET /mtb_expantions/1
  # GET /mtb_expantions/1.json
  def show
    @mtb_expantion = MtbExpantion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mtb_expantion }
    end
  end

  # GET /mtb_expantions/new
  # GET /mtb_expantions/new.json
  def new
    @mtb_expantion = MtbExpantion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mtb_expantion }
    end
  end

  # GET /mtb_expantions/1/edit
  def edit
    @mtb_expantion = MtbExpantion.find(params[:id])
  end

  # POST /mtb_expantions
  # POST /mtb_expantions.json
  def create
    @mtb_expantion = MtbExpantion.new(params[:mtb_expantion])

    respond_to do |format|
      if @mtb_expantion.save
        format.html { redirect_to @mtb_expantion, notice: 'Mtb expantion was successfully created.' }
        format.json { render json: @mtb_expantion, status: :created, location: @mtb_expantion }
      else
        format.html { render action: "new" }
        format.json { render json: @mtb_expantion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mtb_expantions/1
  # PUT /mtb_expantions/1.json
  def update
    @mtb_expantion = MtbExpantion.find(params[:id])

    respond_to do |format|
      if @mtb_expantion.update_attributes(params[:mtb_expantion])
        format.html { redirect_to @mtb_expantion, notice: 'Mtb expantion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mtb_expantion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mtb_expantions/1
  # DELETE /mtb_expantions/1.json
  def destroy
    @mtb_expantion = MtbExpantion.find(params[:id])
    @mtb_expantion.destroy

    respond_to do |format|
      format.html { redirect_to mtb_expantions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mtb_expantions_helper.rb
module MtbExpantionsHelper
end

app/views/mtb_expantions/_form.html.erb
<%= form_for(@mtb_expantion) do |f| %>
  <% if @mtb_expantion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mtb_expantion.errors.count, "error") %> prohibited this mtb_expantion from being saved:</h2>

      <ul>
      <% @mtb_expantion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :released_at %><br />
    <%= f.date_select :released_at %>
  </div>
  <div class="field">
    <%= f.label :mtb_publisher_id %><br />
    <%= f.number_field :mtb_publisher_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mtb_expantions/edit.html.erb
<h1>Editing mtb_expantion</h1>

<%= render 'form' %>

<%= link_to 'Show', @mtb_expantion %> |
<%= link_to 'Back', mtb_expantions_path %>

app/views/mtb_expantions/index.html.erb
<h1>Listing mtb_expantions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Released at</th>
    <th>Mtb publisher</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mtb_expantions.each do |mtb_expantion| %>
  <tr>
    <td><%= mtb_expantion.name %></td>
    <td><%= mtb_expantion.released_at %></td>
    <td><%= mtb_expantion.mtb_publisher_id %></td>
    <td><%= link_to 'Show', mtb_expantion %></td>
    <td><%= link_to 'Edit', edit_mtb_expantion_path(mtb_expantion) %></td>
    <td><%= link_to 'Destroy', mtb_expantion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mtb expantion', new_mtb_expantion_path %>

app/views/mtb_expantions/new.html.erb
<h1>New mtb_expantion</h1>

<%= render 'form' %>

<%= link_to 'Back', mtb_expantions_path %>

app/views/mtb_expantions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mtb_expantion.name %>
</p>

<p>
  <b>Released at:</b>
  <%= @mtb_expantion.released_at %>
</p>

<p>
  <b>Mtb publisher:</b>
  <%= @mtb_expantion.mtb_publisher_id %>
</p>


<%= link_to 'Edit', edit_mtb_expantion_path(@mtb_expantion) %> |
<%= link_to 'Back', mtb_expantions_path %>