config/routes.rb
Dsg::Application.routes.draw do
  resources :mtb_among_card_types

  resources :mtb_among_card_expantions

  resources :mtb_cards

  resources :mtb_expantions

  resources :mtb_publishers

  resources :mtb_card_types

  match ':controller(/:action(/:id))(.:format)'
end

app/models/mtb_card.rb
class MtbCard < ActiveRecord::Base
  attr_accessible :action, :buy, :card, :coin, :cost, :jname, :name, :need_pot, :text, :victory, :virtual_coin, :vitory_token
end

app/models/mtb_card_type.rb
class MtbCardType < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/mtb_cards_controller.rb
class MtbCardsController < ApplicationController
  # GET /mtb_cards
  # GET /mtb_cards.json
  def index
    @mtb_cards = MtbCard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mtb_cards }
    end
  end

  # GET /mtb_cards/1
  # GET /mtb_cards/1.json
  def show
    @mtb_card = MtbCard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mtb_card }
    end
  end

  # GET /mtb_cards/new
  # GET /mtb_cards/new.json
  def new
    @mtb_card = MtbCard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mtb_card }
    end
  end

  # GET /mtb_cards/1/edit
  def edit
    @mtb_card = MtbCard.find(params[:id])
  end

  # POST /mtb_cards
  # POST /mtb_cards.json
  def create
    @mtb_card = MtbCard.new(params[:mtb_card])

    respond_to do |format|
      if @mtb_card.save
        format.html { redirect_to @mtb_card, notice: 'Mtb card was successfully created.' }
        format.json { render json: @mtb_card, status: :created, location: @mtb_card }
      else
        format.html { render action: "new" }
        format.json { render json: @mtb_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mtb_cards/1
  # PUT /mtb_cards/1.json
  def update
    @mtb_card = MtbCard.find(params[:id])

    respond_to do |format|
      if @mtb_card.update_attributes(params[:mtb_card])
        format.html { redirect_to @mtb_card, notice: 'Mtb card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mtb_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mtb_cards/1
  # DELETE /mtb_cards/1.json
  def destroy
    @mtb_card = MtbCard.find(params[:id])
    @mtb_card.destroy

    respond_to do |format|
      format.html { redirect_to mtb_cards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mtb_cards_helper.rb
module MtbCardsHelper
end

app/views/mtb_cards/_form.html.erb
<%= form_for(@mtb_card) do |f| %>
  <% if @mtb_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mtb_card.errors.count, "error") %> prohibited this mtb_card from being saved:</h2>

      <ul>
      <% @mtb_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :jname %><br />
    <%= f.text_field :jname %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :need_pot %><br />
    <%= f.number_field :need_pot %>
  </div>
  <div class="field">
    <%= f.label :coin %><br />
    <%= f.number_field :coin %>
  </div>
  <div class="field">
    <%= f.label :victory %><br />
    <%= f.number_field :victory %>
  </div>
  <div class="field">
    <%= f.label :card %><br />
    <%= f.number_field :card %>
  </div>
  <div class="field">
    <%= f.label :action %><br />
    <%= f.number_field :action %>
  </div>
  <div class="field">
    <%= f.label :buy %><br />
    <%= f.number_field :buy %>
  </div>
  <div class="field">
    <%= f.label :virtual_coin %><br />
    <%= f.number_field :virtual_coin %>
  </div>
  <div class="field">
    <%= f.label :vitory_token %><br />
    <%= f.number_field :vitory_token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mtb_cards/edit.html.erb
<h1>Editing mtb_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @mtb_card %> |
<%= link_to 'Back', mtb_cards_path %>

app/views/mtb_cards/index.html.erb
<h1>Listing mtb_cards</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Jname</th>
    <th>Text</th>
    <th>Cost</th>
    <th>Need pot</th>
    <th>Coin</th>
    <th>Victory</th>
    <th>Card</th>
    <th>Action</th>
    <th>Buy</th>
    <th>Virtual coin</th>
    <th>Vitory token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mtb_cards.each do |mtb_card| %>
  <tr>
    <td><%= mtb_card.name %></td>
    <td><%= mtb_card.jname %></td>
    <td><%= mtb_card.text %></td>
    <td><%= mtb_card.cost %></td>
    <td><%= mtb_card.need_pot %></td>
    <td><%= mtb_card.coin %></td>
    <td><%= mtb_card.victory %></td>
    <td><%= mtb_card.card %></td>
    <td><%= mtb_card.action %></td>
    <td><%= mtb_card.buy %></td>
    <td><%= mtb_card.virtual_coin %></td>
    <td><%= mtb_card.vitory_token %></td>
    <td><%= link_to 'Show', mtb_card %></td>
    <td><%= link_to 'Edit', edit_mtb_card_path(mtb_card) %></td>
    <td><%= link_to 'Destroy', mtb_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mtb card', new_mtb_card_path %>

app/views/mtb_cards/new.html.erb
<h1>New mtb_card</h1>

<%= render 'form' %>

<%= link_to 'Back', mtb_cards_path %>

app/views/mtb_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mtb_card.name %>
</p>

<p>
  <b>Jname:</b>
  <%= @mtb_card.jname %>
</p>

<p>
  <b>Text:</b>
  <%= @mtb_card.text %>
</p>

<p>
  <b>Cost:</b>
  <%= @mtb_card.cost %>
</p>

<p>
  <b>Need pot:</b>
  <%= @mtb_card.need_pot %>
</p>

<p>
  <b>Coin:</b>
  <%= @mtb_card.coin %>
</p>

<p>
  <b>Victory:</b>
  <%= @mtb_card.victory %>
</p>

<p>
  <b>Card:</b>
  <%= @mtb_card.card %>
</p>

<p>
  <b>Action:</b>
  <%= @mtb_card.action %>
</p>

<p>
  <b>Buy:</b>
  <%= @mtb_card.buy %>
</p>

<p>
  <b>Virtual coin:</b>
  <%= @mtb_card.virtual_coin %>
</p>

<p>
  <b>Vitory token:</b>
  <%= @mtb_card.vitory_token %>
</p>


<%= link_to 'Edit', edit_mtb_card_path(@mtb_card) %> |
<%= link_to 'Back', mtb_cards_path %>