config/routes.rb
Dsg::Application.routes.draw do
  resources :mtb_among_card_types

  resources :mtb_among_card_expantions

  resources :mtb_cards

  resources :mtb_expantions

  resources :mtb_publishers

  resources :mtb_card_types

  match ':controller(/:action(/:id))(.:format)'
end

app/models/mtb_among_card_expantion.rb
class MtbAmongCardExpantion < ActiveRecord::Base
  attr_accessible :mtb_card_id, :mtb_expantion_id, :override_name, :override_text
end

app/controllers/mtb_among_card_expantions_controller.rb
class MtbAmongCardExpantionsController < ApplicationController
  # GET /mtb_among_card_expantions
  # GET /mtb_among_card_expantions.json
  def index
    @mtb_among_card_expantions = MtbAmongCardExpantion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mtb_among_card_expantions }
    end
  end

  # GET /mtb_among_card_expantions/1
  # GET /mtb_among_card_expantions/1.json
  def show
    @mtb_among_card_expantion = MtbAmongCardExpantion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mtb_among_card_expantion }
    end
  end

  # GET /mtb_among_card_expantions/new
  # GET /mtb_among_card_expantions/new.json
  def new
    @mtb_among_card_expantion = MtbAmongCardExpantion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mtb_among_card_expantion }
    end
  end

  # GET /mtb_among_card_expantions/1/edit
  def edit
    @mtb_among_card_expantion = MtbAmongCardExpantion.find(params[:id])
  end

  # POST /mtb_among_card_expantions
  # POST /mtb_among_card_expantions.json
  def create
    @mtb_among_card_expantion = MtbAmongCardExpantion.new(params[:mtb_among_card_expantion])

    respond_to do |format|
      if @mtb_among_card_expantion.save
        format.html { redirect_to @mtb_among_card_expantion, notice: 'Mtb among card expantion was successfully created.' }
        format.json { render json: @mtb_among_card_expantion, status: :created, location: @mtb_among_card_expantion }
      else
        format.html { render action: "new" }
        format.json { render json: @mtb_among_card_expantion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mtb_among_card_expantions/1
  # PUT /mtb_among_card_expantions/1.json
  def update
    @mtb_among_card_expantion = MtbAmongCardExpantion.find(params[:id])

    respond_to do |format|
      if @mtb_among_card_expantion.update_attributes(params[:mtb_among_card_expantion])
        format.html { redirect_to @mtb_among_card_expantion, notice: 'Mtb among card expantion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mtb_among_card_expantion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mtb_among_card_expantions/1
  # DELETE /mtb_among_card_expantions/1.json
  def destroy
    @mtb_among_card_expantion = MtbAmongCardExpantion.find(params[:id])
    @mtb_among_card_expantion.destroy

    respond_to do |format|
      format.html { redirect_to mtb_among_card_expantions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mtb_among_card_expantions_helper.rb
module MtbAmongCardExpantionsHelper
end

app/views/mtb_among_card_expantions/_form.html.erb
<%= form_for(@mtb_among_card_expantion) do |f| %>
  <% if @mtb_among_card_expantion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mtb_among_card_expantion.errors.count, "error") %> prohibited this mtb_among_card_expantion from being saved:</h2>

      <ul>
      <% @mtb_among_card_expantion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mtb_card_id %><br />
    <%= f.number_field :mtb_card_id %>
  </div>
  <div class="field">
    <%= f.label :mtb_expantion_id %><br />
    <%= f.number_field :mtb_expantion_id %>
  </div>
  <div class="field">
    <%= f.label :override_name %><br />
    <%= f.text_field :override_name %>
  </div>
  <div class="field">
    <%= f.label :override_text %><br />
    <%= f.text_area :override_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mtb_among_card_expantions/edit.html.erb
<h1>Editing mtb_among_card_expantion</h1>

<%= render 'form' %>

<%= link_to 'Show', @mtb_among_card_expantion %> |
<%= link_to 'Back', mtb_among_card_expantions_path %>

app/views/mtb_among_card_expantions/index.html.erb
<h1>Listing mtb_among_card_expantions</h1>

<table>
  <tr>
    <th>Mtb card</th>
    <th>Mtb expantion</th>
    <th>Override name</th>
    <th>Override text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mtb_among_card_expantions.each do |mtb_among_card_expantion| %>
  <tr>
    <td><%= mtb_among_card_expantion.mtb_card_id %></td>
    <td><%= mtb_among_card_expantion.mtb_expantion_id %></td>
    <td><%= mtb_among_card_expantion.override_name %></td>
    <td><%= mtb_among_card_expantion.override_text %></td>
    <td><%= link_to 'Show', mtb_among_card_expantion %></td>
    <td><%= link_to 'Edit', edit_mtb_among_card_expantion_path(mtb_among_card_expantion) %></td>
    <td><%= link_to 'Destroy', mtb_among_card_expantion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mtb among card expantion', new_mtb_among_card_expantion_path %>

app/views/mtb_among_card_expantions/new.html.erb
<h1>New mtb_among_card_expantion</h1>

<%= render 'form' %>

<%= link_to 'Back', mtb_among_card_expantions_path %>

app/views/mtb_among_card_expantions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mtb card:</b>
  <%= @mtb_among_card_expantion.mtb_card_id %>
</p>

<p>
  <b>Mtb expantion:</b>
  <%= @mtb_among_card_expantion.mtb_expantion_id %>
</p>

<p>
  <b>Override name:</b>
  <%= @mtb_among_card_expantion.override_name %>
</p>

<p>
  <b>Override text:</b>
  <%= @mtb_among_card_expantion.override_text %>
</p>


<%= link_to 'Edit', edit_mtb_among_card_expantion_path(@mtb_among_card_expantion) %> |
<%= link_to 'Back', mtb_among_card_expantions_path %>