config/routes.rb
Dsg::Application.routes.draw do
  resources :mtb_among_card_types

  resources :mtb_among_card_expantions

  resources :mtb_cards

  resources :mtb_expantions

  resources :mtb_publishers

  resources :mtb_card_types

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/mtb_among_card_types_controller.rb
class MtbAmongCardTypesController < ApplicationController
  # GET /mtb_among_card_types
  # GET /mtb_among_card_types.json
  def index
    @mtb_among_card_types = MtbAmongCardType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mtb_among_card_types }
    end
  end

  # GET /mtb_among_card_types/1
  # GET /mtb_among_card_types/1.json
  def show
    @mtb_among_card_type = MtbAmongCardType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mtb_among_card_type }
    end
  end

  # GET /mtb_among_card_types/new
  # GET /mtb_among_card_types/new.json
  def new
    @mtb_among_card_type = MtbAmongCardType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mtb_among_card_type }
    end
  end

  # GET /mtb_among_card_types/1/edit
  def edit
    @mtb_among_card_type = MtbAmongCardType.find(params[:id])
  end

  # POST /mtb_among_card_types
  # POST /mtb_among_card_types.json
  def create
    @mtb_among_card_type = MtbAmongCardType.new(params[:mtb_among_card_type])

    respond_to do |format|
      if @mtb_among_card_type.save
        format.html { redirect_to @mtb_among_card_type, notice: 'Mtb among card type was successfully created.' }
        format.json { render json: @mtb_among_card_type, status: :created, location: @mtb_among_card_type }
      else
        format.html { render action: "new" }
        format.json { render json: @mtb_among_card_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mtb_among_card_types/1
  # PUT /mtb_among_card_types/1.json
  def update
    @mtb_among_card_type = MtbAmongCardType.find(params[:id])

    respond_to do |format|
      if @mtb_among_card_type.update_attributes(params[:mtb_among_card_type])
        format.html { redirect_to @mtb_among_card_type, notice: 'Mtb among card type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mtb_among_card_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mtb_among_card_types/1
  # DELETE /mtb_among_card_types/1.json
  def destroy
    @mtb_among_card_type = MtbAmongCardType.find(params[:id])
    @mtb_among_card_type.destroy

    respond_to do |format|
      format.html { redirect_to mtb_among_card_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mtb_among_card_types_helper.rb
module MtbAmongCardTypesHelper
end

app/views/mtb_among_card_types/_form.html.erb
<%= form_for(@mtb_among_card_type) do |f| %>
  <% if @mtb_among_card_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mtb_among_card_type.errors.count, "error") %> prohibited this mtb_among_card_type from being saved:</h2>

      <ul>
      <% @mtb_among_card_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mtb_card_id %><br />
    <%= f.number_field :mtb_card_id %>
  </div>
  <div class="field">
    <%= f.label :mtb_card_type_id %><br />
    <%= f.number_field :mtb_card_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mtb_among_card_types/edit.html.erb
<h1>Editing mtb_among_card_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @mtb_among_card_type %> |
<%= link_to 'Back', mtb_among_card_types_path %>

app/views/mtb_among_card_types/index.html.erb
<h1>Listing mtb_among_card_types</h1>

<table>
  <tr>
    <th>Mtb card</th>
    <th>Mtb card type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mtb_among_card_types.each do |mtb_among_card_type| %>
  <tr>
    <td><%= mtb_among_card_type.mtb_card_id %></td>
    <td><%= mtb_among_card_type.mtb_card_type_id %></td>
    <td><%= link_to 'Show', mtb_among_card_type %></td>
    <td><%= link_to 'Edit', edit_mtb_among_card_type_path(mtb_among_card_type) %></td>
    <td><%= link_to 'Destroy', mtb_among_card_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mtb among card type', new_mtb_among_card_type_path %>

app/views/mtb_among_card_types/new.html.erb
<h1>New mtb_among_card_type</h1>

<%= render 'form' %>

<%= link_to 'Back', mtb_among_card_types_path %>

app/views/mtb_among_card_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mtb card:</b>
  <%= @mtb_among_card_type.mtb_card_id %>
</p>

<p>
  <b>Mtb card type:</b>
  <%= @mtb_among_card_type.mtb_card_type_id %>
</p>


<%= link_to 'Edit', edit_mtb_among_card_type_path(@mtb_among_card_type) %> |
<%= link_to 'Back', mtb_among_card_types_path %>